
/* keyword definitions */


/* SET variables - see options.c */ 

#define KW_ABSTOL           "abstol"
#define KW_ACCT             "acct"
#define KW_APPENDWRITE      "appendwrite"
#define KW_BYPASS           "bypass"
#define KW_CHECKITERATE     "checkiterate"
#define KW_CHGTOL           "chgtol"
#define KW_COLOR_NUM        "color<num>"
#define KW_CPDEBUG          "cpdebug"
#define KW_CPTIME           "cptime"
#define KW_CURPLOT          "curplot"
#define KW_CURPLOTNAME      "curplotname"
#define KW_CURPLOTTITLE     "curplottitle"
#define KW_CURPLOTDATE      "curplotdate"
#define KW_DEBUG            "debug"
#define KW_DEFAD            "defad"
#define KW_DEFAS            "defas"
#define KW_DEFL             "defl"
#define KW_DEFW             "defw"
#define KW_DEVICE           "device"
#define KW_DISPLAY          "display"
#define KW_DONTPLOT         "dontplot"
#define KW_EDITOR           "editor"
#define KW_FILETYPE         "filetype"
#define KW_FOURGRIDSIZE     "fourgridsize"
#define KW_GEOMETRY         "geometry"
#define KW_GEOMETRY_NUM     "geometry<num>"
#define KW_GMIN             "gmin"
#define KW_GRIDSIZE         "gridsize"
#define KW_GRIDSTYLE        "gridstyle"
#define KW_HCOPYDEV         "hcopydev"
#define KW_HEIGHT           "height"
#define KW_HELPPATH         "helppath"
#define KW_HELPREGFONT      "helpregfont"
#define KW_HELPBOLDFONT     "helpboldfont"
#define KW_HELPITALICFONT   "helpitalicfont"
#define KW_HELPTITLEFONT    "helptitlefont"
#define KW_HELPBUTTONFONT   "helpbuttonfont"
#define KW_HELPINITXPOS     "helpinitxpos"
#define KW_HELPINITYPOS     "helpinitypos"
#define KW_HELPBUTTONSTYLE  "helpbuttonstyle"
#define KW_HISTORY          "history"
#define KW_HITUSERTP        "hitusertp"
#define KW_IGNOREEOF        "ignoreeof"
#define KW_ITL1             "itl1"
#define KW_ITL2             "itl2"
#define KW_ITL3             "itl3"
#define KW_ITL4             "itl4"
#define KW_ITL5             "itl5"
#define KW_JJDPHIMAX        "jjdphimax"
#define KW_LIMPTS           "limpts"
#define KW_LIST             "list"
#define KW_MAXWINS          "maxwins"
#define KW_MODELCARD        "modelcard"
#define KW_NFREQS           "nfreqs"
#define KW_NOASCIIPLOTVALUE "noasciiplotvalue"
#define KW_NOASKQUIT        "noaskquit"
#define KW_NOBJTHACK        "nobjthack"
#define KW_NOBREAK          "nobreak"
#define KW_NOCC             "nocc"
#define KW_NOCLOBBER        "noclobber"
#define KW_NODE             "node"
#define KW_NOGLOB           "noglob"
/* KW_NOGRID - see PLOT args */
#define KW_NOITER           "noiter"
#define KW_NOMOREMODE       "nomoremode"
#define KW_NONOMATCH        "nonomatch"
#define KW_NOPAGE           "nopage"
#define KW_NOPARSE          "noparse"
#define KW_NOPRINTSCALE     "noprintscale"
#define KW_NOSORT           "nosort"
#define KW_NOSUBCKT         "nosubckt"
#define KW_NOSWAP           "noswap"
#define KW_NOUSERTP         "nousertp"
#define KW_NUMDGT           "numdgt"
#define KW_OPTS             "opts"
#define KW_PIVREL           "pivrel"
#define KW_PIVTOL           "pivtol"
#define KW_PLOTS            "plots"
#define KW_PLOTSTYLE        "plotstyle"
#define KW_POINTCHARS       "pointchars"
#define KW_POLYDEGREE       "polydegree"
#define KW_POLYSTEPS        "polysteps"
#define KW_PROGRAM          "program"
#define KW_PROMPT           "prompt"
#define KW_RAWFILE          "rawfile"
#define KW_RAWFILEPREC      "rawfileprec"
#define KW_RELTOL           "reltol"
#define KW_RENUMBER         "renumber"
#define KW_RHOST            "rhost"
#define KW_RPROGRAM         "rprogram"
#define KW_SLOWPLOT         "slowplot"
#define KW_SOURCEPATH       "sourcepath"
#define KW_SPICEPATH        "spicepath"
#define KW_STRICTNUMPARSE   "strictnumparse"
#define KW_SUBEND           "subend"
#define KW_SUBINVOKE        "subinvoke"
#define KW_SUBSTART         "substart"
#define KW_TERM             "term"
#define KW_TICMARKS         "ticmarks"
#define KW_TEMP             "temp"
#define KW_TNOM             "tnom"
#define KW_TRTOL            "trtol"
#define KW_UNITS            "units"
#define KW_UNIXCOM          "unixcom"
#define KW_VNTOL            "vntol"
#define KW_WIDTH            "width"
#define KW_XBRUSHHEIGHT     "xbrushheight"
#define KW_XBRUSHWIDTH      "xbrushwidth"
#define KW_XFONT            "xfont"

/* debug options */

#define KW_ASYNC            "async"
#define KW_CONTROL          "control"
#define KW_CSHPAR           "cshpar"
#define KW_EVAL             "eval"
#define KW_GINTERFACE       "ginterface"
#define KW_GRAF             "graf"
#define KW_PARSER           "parser"
#define KW_SIMINTERFACE     "siminterface"
#define KW_VECDB            "vecdb"

/* listing keywords */

#define KW_DECK             "deck"
#define KW_EXPAND           "expand"
#define KW_LOGICAL          "logical"
#define KW_PHYSICAL         "physical"

/* stop keywords */

#define KW_AFTER            "after"
#define KW_WHEN             "when"

/* plot keywords */

#define KW_COMBPLOT         "combplot"
#define KW_LINGRID          "lingrid"
#define KW_LINPLOT          "linplot"
#define KW_LOGLOG           "loglog"
#define KW_NEW              "new"
#define KW_NOGRID           "nogrid"
#define KW_NOINTERP         "nointerp"
#define KW_POINTPLOT        "pointplot"
#define KW_POLAR            "polar"
#define KW_SAMEP            "samep"
#define KW_SMITH            "smith"
#define KW_TITLE            "title"
#define KW_VS               "vs"
#define KW_XCOMP            "xcomp"
#define KW_XCOMPRESS        "xcompress"
#define KW_XDEL             "xdel"
#define KW_XDELTA           "xdelta"
#define KW_XIND             "xind"
#define KW_XINDICES         "xindices"
#define KW_XL               "xl"
#define KW_XLABEL           "xlabel"
#define KW_XLIMIT           "xlimit"
#define KW_XLOG             "xlog"
#define KW_YDEL             "ydel"
#define KW_YDELTA           "ydelta"
#define KW_YL               "yl"
#define KW_YLABEL           "ylabel"
#define KW_YLIMIT           "ylimit"
#define KW_YLOG             "ylog"

/* rusage keywords */

#define KW_ACCEPT           "accept"
#define KW_ALL              "all"
#define KW_ELAPSED          "elapsed"
#define KW_EVERYTHING       "everything"
#define KW_FAULTS           "faults"
#define KW_FILLIN           "fillin"
#define KW_LOADTIME         "loadtime"
#define KW_LUTIME           "lutime"
#define KW_MATSIZE          "matsize"
#define KW_NONZERO          "nonzero"
#define KW_REJECTED         "rejected"
#define KW_SOLVETIME        "solvetime"
#define KW_SPACE            "space"
#define KW_TIME             "time"
#define KW_TOTALTIME        "totaltime"
#define KW_TOTITER          "totiter"
#define KW_TRANITER         "traniter"
#define KW_TRANPOINTS       "tranpoints"
#define KW_TRANSOLVETIME    "transolvetime"
#define KW_TRANTIME         "trantime"

/* vectors */

#define KW_ANONYMOUS        "Anonymous"
#define KW_UNKNOWN          "unknown"

/* filetypes */

#define KW_ASCII            "ascii"
#define KW_BINARY           "binary"
#define KW_OCT              "oct"

/* print keywords */

#define KW_COL              "col"
#define KW_LINE             "line"

/* analysis keywords */

#define KW_AC               "ac"
#define KW_DC               "dc"
#define KW_DEFAULT          "default"
#define KW_OP               "op"
#define KW_OPTIONS          "options"
#define KW_PZ               "pz"
#define KW_RESUME           "resume"
#define KW_RUN              "run"
#define KW_TRAN             "tran"
#define KW_TSTART           "tstart"
#define KW_TSTEP            "tstep"
#define KW_TSTOP            "tstop"


/* unsupported */

#define KW_LVLTIM           "lvltim"
#define KW_MAXORD           "maxord"
#define KW_METHOD           "method"

/* obsolete */

#define KW_LIMTIM           "limtim"
#define KW_LVLCOD           "lvlcod"
#define KW_NOMOD            "nomod"


/* button styles */

#define KW_CENTER           "center"
#define KW_LEFT             "left"
#define KW_UNIF             "unif"
