
TARGET = mos
$(TARGET):

###include makedefs
CFILES = \
mos.c \
mosacld.c \
mosask.c \
mosconv.c \
mosdist.c \
mosdset.c \
moseq.c \
mosic.c \
mosload.c \
mosmask.c \
mosmpar.c \
mosnoi.c \
mospar.c \
mospzld.c \
mosset.c \
mostemp.c \
mostrun.c

HDRS = \
mosdefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
