
TARGET = bsim3
$(TARGET):

###include makedefs
CFILES = \
	b3.c		\
	b3acld.c	\
	b3ask.c		\
	b3check.c	\
	b3cvtest.c	\
	b3del.c		\
	b3dest.c	\
	b3getic.c	\
	b3ld.c		\
	b3mask.c	\
	b3mdel.c	\
	b3mpar.c	\
	b3noi.c		\
	b3par.c		\
	b3pzld.c	\
	b3set.c		\
	b3temp.c	\
	b3trunc.c	\
	bsim3init.c

HDRS = \
	bsim3def.h	\
	bsim3ext.h	\
	bsim3init.h	\
	bsim3itf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
