
TARGET = txl
$(TARGET):

###include makedefs
CFILES = \
	txl.c      \
	txlacct.c  \
	txlask.c   \
	txldest.c  \
	txlfbr.c   \
	txlload.c  \
	txlmdel.c  \
	txlparam.c \
	txldel.c   \
	txlmask.c  \
	txlmpar.c  \
	txlsetup.c \
	txlinit.c

HDRS = \
	txldefs.h  \
	txlext.h   \
	txlinit.h  \
	txlitf.h   \
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
