
TARGET = jfet
$(TARGET):

###include makedefs
CFILES = \
jfet.c \
jfetacld.c \
jfetask.c \
jfetdist.c \
jfetdset.c \
jfetic.c \
jfetload.c \
jfetmask.c \
jfetmpar.c \
jfetnoi.c \
jfetpar.c \
jfetprse.c \
jfetpzld.c \
jfetset.c \
jfettemp.c \
jfettrun.c

HDRS = \
jfetdefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
