
TARGET = dio
$(TARGET):

###include makedefs
CFILES = \
dio.c \
dioacld.c \
dioask.c \
dioconv.c \
diodisto.c \
diodset.c \
diogetic.c \
dioload.c \
diomask.c \
diompar.c \
dionoise.c \
dioparam.c \
dioparse.c \
diopzld.c \
diosetup.c \
diotemp.c \
diotrunc.c

HDRS = \
diodefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
