
TARGET = ltra
$(TARGET):

###include makedefs
CFILES = \
	ltra.c		\
	ltraacct.c	\
	ltraacld.c	\
	ltraask.c	\
	ltradel.c	\
	ltradest.c	\
	ltrainit.c	\
	ltraload.c	\
	ltramask.c	\
	ltramdel.c	\
	ltramisc.c	\
	ltrampar.c	\
	ltrapar.c	\
	ltraset.c	\
	ltratemp.c	\
	ltratrun.c

HDRS = \
	ltradefs.h	\
	ltraext.h	\
	ltrainit.h	\
	ltraitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
