
TARGET = nbjt.so
all : $(TARGET)

###include makedefs
CFILES = \
	nbjt.c		\
	nbjtacld.c	\
	nbjtask.c	\
	nbjtdel.c	\
	nbjtdest.c	\
	nbjtdump.c	\
	nbjtinit.c	\
	nbjtload.c	\
	nbjtmdel.c	\
	nbjtmpar.c	\
	nbjtparm.c	\
	nbjtpzld.c	\
	nbjtset.c	\
	nbjttemp.c	\
	nbjttrun.c	

HDRS = \
	nbjtdefs.h	\
	nbjtext.h	\
	nbjtinit.h	\
	nbjtitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
