
TARGET = jj
$(TARGET):

###include makedefs
CFILES = \
jj.c \
jjacct.c \
jjask.c \
jjgetic.c \
jjload.c \
jjmask.c \
jjmpar.c \
jjparam.c \
jjparse.c \
jjsetup.c \
jjtrunc.c

HDRS = \
jjdefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
