
TARGET = bjt
$(TARGET):

###include makedefs
CFILES = \
	bjt.c		\
	bjtacld.c	\
	bjtask.c	\
	bjtconv.c	\
	bjtdel.c	\
	bjtdest.c	\
	bjtdisto.c	\
	bjtdset.c	\
	bjtgetic.c	\
	bjtinit.c	\
	bjtload.c	\
	bjtmask.c	\
	bjtmdel.c	\
	bjtmpar.c	\
	bjtnoise.c	\
	bjtparam.c	\
	bjtpzld.c	\
	bjtsacl.c	\
	bjtsetup.c	\
	bjtsload.c	\
	bjtsprt.c	\
	bjtsset.c	\
	bjtsupd.c	\
	bjttemp.c	\
	bjttrunc.c

HDRS = \
	bjtdefs.h	\
	bjtdset.h	\
	bjtext.h	\
	bjtinit.h	\
	bjtitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
