
TARGET = src
$(TARGET):

###include makedefs
CFILES = \
src.c \
srcacld.c \
srcask.c \
srcconv.c \
srcdel.c \
srcdest.c \
srcfbr.c \
srcload.c \
srcmdel.c \
srcpar.c \
srcparse.c \
srcpzld.c \
srcset.c

HDRS = \
srcdefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
