
TARGET = sw
$(TARGET):

###include makedefs
CFILES = \
sw.c \
swacload.c \
swask.c \
swload.c \
swmask.c \
swmparam.c \
swnoise.c \
swparam.c \
swparse.c \
swpzload.c \
swsetup.c

HDRS = \
swdefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
