
TARGET = nbjt2.so
all : $(TARGET)

###include makedefs
CFILES = \
	nbt2.c		\
	nbt2acld.c	\
	nbt2ask.c	\
	nbt2del.c	\
	nbt2dest.c	\
	nbt2dump.c	\
	nbt2init.c	\
	nbt2load.c	\
	nbt2mdel.c	\
	nbt2mpar.c	\
	nbt2parm.c	\
	nbt2pzld.c	\
	nbt2set.c	\
	nbt2temp.c	\
	nbt2trun.c	

HDRS = \
	nbjt2def.h	\
	nbjt2ext.h	\
	nbt2init.h	\
	nbjt2itf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
