
TARGET = dio
$(TARGET):

###include makedefs
CFILES = \
	dio.c		\
	dioacld.c	\
	dioask.c	\
	dioconv.c	\
	diodel.c	\
	diodest.c	\
	diodisto.c	\
	diodset.c	\
	diogetic.c	\
	dioinit.c	\
	dioload.c	\
	diomask.c	\
	diomdel.c	\
	diompar.c	\
	dionoise.c	\
	dioparam.c	\
	diopzld.c	\
	diosacl.c	\
	diosetup.c	\
	diosload.c	\
	diosprt.c	\
	diosset.c	\
	diosupd.c	\
	diotemp.c	\
	diotrunc.c

HDRS = \
	diodefs.h	\
	dioext.h	\
	dioinit.h	\
	dioitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
