
TARGET = sw
$(TARGET):

###include makedefs
CFILES = \
	sw.c		\
	swacload.c	\
	swask.c		\
	swdelete.c	\
	swdest.c	\
	swinit.c	\
	swload.c	\
	swmask.c	\
	swmdel.c	\
	swmparam.c	\
	swnoise.c	\
	swparam.c	\
	swpzload.c	\
	swsetup.c	\
	swtrunc.c 

HDRS = \
	swdefs.h	\
	swext.h		\
	swinit.h	\
	switf.h		\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
