
TARGET = bsim3v0
$(TARGET):

###include makedefs
CFILES = \
	b3v0.c		\
	b3v0acld.c	\
	b3v0ask.c	\
	b3v0cvtest.c	\
	b3v0del.c	\
	b3v0dest.c	\
	b3v0getic.c	\
	b3v0ld.c	\
	b3v0mask.c	\
	b3v0mdel.c	\
	b3v0mpar.c	\
	b3v0noi.c	\
	b3v0par.c	\
	b3v0pzld.c	\
	b3v0set.c	\
	b3v0temp.c	\
	b3v0trunc.c	\
	bsim3v0init.c

HDRS = \
	bsim3v0def.h	\
	bsim3v0ext.h	\
	bsim3v0init.h	\
	bsim3v0itf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
