
TARGET = bsim3v1a
$(TARGET):

###include makedefs
CFILES = \
	b3v1a.c		\
	b3v1aacld.c	\
	b3v1aask.c	\
	b3v1acvtest.c	\
	b3v1adel.c	\
	b3v1adest.c	\
	b3v1agetic.c	\
	b3v1ald.c	\
	b3v1amask.c	\
	b3v1amdel.c	\
	b3v1ampar.c	\
	b3v1anoi.c	\
	b3v1apar.c	\
	b3v1apzld.c	\
	b3v1aset.c	\
	b3v1atemp.c	\
	b3v1atrunc.c	\
	bsim3v1ainit.c

HDRS = \
	bsim3v1adef.h	\
	bsim3v1aext.h	\
	bsim3v1ainit.h	\
	bsim3v1aitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
