
TARGET = tra
$(TARGET):

###include makedefs
CFILES = \
tra.c \
traacct.c \
traacld.c \
traask.c \
traload.c \
traparam.c \
traparse.c \
trasetup.c \
tratemp.c \
tratrunc.c

HDRS = \
tradefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
