
TARGET = numd2.so
all : $(TARGET)

###include makedefs
CFILES = \
	nud2.c		\
	nud2acld.c	\
	nud2ask.c	\
	nud2del.c	\
	nud2dest.c	\
	nud2dump.c	\
	numd2init.c	\
	nud2load.c	\
	nud2mdel.c	\
	nud2mpar.c	\
	nud2parm.c	\
	nud2pzld.c	\
	nud2set.c	\
	nud2temp.c	\
	nud2trun.c	

HDRS = \
	numd2def.h	\
	numd2ext.h	\
	numd2init.h	\
	numd2itf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
