
TARGET = bsim3soipd
$(TARGET):

###include makedefs
CFILES = \
	b3soipd.c	\
	b3soipdacld.c	\
	b3soipdask.c	\
	b3soipdcheck.c	\
	b3soipdcvtest.c	\
	b3soipddel.c	\
	b3soipddest.c	\
	b3soipdgetic.c	\
	b3soipdld.c	\
	b3soipdmask.c	\
	b3soipdmdel.c	\
	b3soipdmpar.c	\
	b3soipdnoi.c	\
	b3soipdpar.c	\
	b3soipdpzld.c	\
	b3soipdset.c	\
	b3soipdtemp.c	\
	b3soipdtrunc.c	\
	b3soipdinit.c

HDRS = \
	b3soipddef.h	\
	b3soipdext.h	\
	b3soipdinit.h	\
	b3soipditf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
