
TARGET = numos.so
all : $(TARGET)

###include makedefs
CFILES = \
	numm.c		\
	nummacld.c	\
	nummask.c	\
	nummdel.c	\
	nummdest.c	\
	nummdump.c	\
	numosinit.c	\
	nummload.c	\
	nummmdel.c	\
	nummmpar.c	\
	nummparm.c	\
	nummpzld.c	\
	nummset.c	\
	nummtemp.c	\
	nummtrun.c	

HDRS = \
	numosdef.h	\
	numosext.h	\
	numosinit.h	\
	numositf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
