
TARGET = bjt
$(TARGET):

###include makedefs
CFILES = \
bjt.c \
bjtacld.c \
bjtask.c \
bjtconv.c \
bjtdisto.c \
bjtdset.c \
bjtgetic.c \
bjtload.c \
bjtmask.c \
bjtmpar.c \
bjtnoise.c \
bjtparam.c \
bjtparse.c \
bjtpzld.c \
bjtsetup.c \
bjttemp.c \
bjttrunc.c

HDRS = \
bjtdefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
