
TARGET = mos3
$(TARGET):

###include makedefs
CFILES = \
	mos3.c		\
	mos3acld.c	\
	mos3ask.c	\
	mos3conv.c	\
	mos3del.c	\
	mos3dest.c	\
	mos3dist.c	\
	mos3dset.c	\
	mos3ic.c	\
	mos3init.c	\
	mos3load.c	\
	mos3mask.c	\
	mos3mdel.c	\
	mos3mpar.c	\
	mos3noi.c	\
	mos3par.c	\
	mos3pzld.c	\
	mos3sacl.c	\
	mos3set.c	\
	mos3sld.c	\
	mos3sprt.c	\
	mos3sset.c	\
	mos3supd.c	\
	mos3temp.c	\
	mos3trun.c

HDRS = \
	mos3defs.h	\
	mos3ext.h	\
	mos3init.h	\
	mos3itf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
