
TARGET = ind
$(TARGET):

###include makedefs
CFILES = \
ind.c \
indacld.c \
indask.c \
indfbr.c \
indic.c \
indload.c \
indparam.c \
indparse.c \
indpzld.c \
indsetup.c \
indtrunc.c \
mutask.c \
mutparam.c \
mutparse.c

HDRS = \
inddefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
