
TARGET = numd.so
all : $(TARGET)

###include makedefs
CFILES = \
	numd.c		\
	numdacld.c	\
	numdask.c	\
	numddel.c	\
	numddest.c	\
	numddump.c	\
	numdinit.c	\
	numdload.c	\
	numdmdel.c	\
	numdmpar.c	\
	numdparm.c	\
	numdpzld.c	\
	numdset.c	\
	numdtemp.c	\
	numdtrun.c	

HDRS = \
	numddefs.h	\
	numdext.h	\
	numdinit.h	\
	numditf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
