
TARGET = res
$(TARGET):

###include makedefs
CFILES = \
	res.c		\
	resask.c	\
	resdel.c	\
	resdest.c	\
	resinit.c	\
	resload.c	\
	resmask.c	\
	resmdel.c	\
	resmpar.c	\
	resnoise.c	\
	resparam.c	\
	respzld.c	\
	ressacl.c	\
	ressetup.c	\
	ressload.c	\
	ressprt.c	\
	ressset.c	\
	restemp.c

HDRS = \
	resdefs.h	\
	resext.h	\
	resinit.h	\
	resitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
