
TARGET = mos1
$(TARGET):

###include makedefs
CFILES = \
	mos1.c		\
	mos1acld.c	\
	mos1ask.c	\
	mos1conv.c	\
	mos1del.c	\
	mos1dest.c	\
	mos1dist.c	\
	mos1dset.c	\
	mos1ic.c	\
	mos1init.c	\
	mos1load.c	\
	mos1mask.c	\
	mos1mdel.c	\
	mos1mpar.c	\
	mos1noi.c	\
	mos1par.c	\
	mos1pzld.c	\
	mos1sacl.c	\
	mos1set.c	\
	mos1sld.c	\
	mos1sprt.c	\
	mos1sset.c	\
	mos1supd.c	\
	mos1temp.c	\
	mos1trun.c

HDRS = \
	mos1defs.h	\
	mos1ext.h	\
	mos1init.h	\
	mos1itf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
