
TARGET = res
$(TARGET):

###include makedefs
CFILES = \
res.c \
resacld.c \
resask.c \
resmask.c \
resmpar.c \
resnoise.c \
resparam.c \
resparse.c \
respzld.c \
ressetup.c \
restemp.c

HDRS = \
resdefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
