
TARGET = mos6
$(TARGET):

###include makedefs
CFILES = \
	mos6.c		\
	mos6ask.c	\
	mos6conv.c	\
	mos6dest.c	\
	mos6ic.c	\
	mos6init.c	\
	mos6load.c	\
	mos6mask.c	\
	mos6mpar.c	\
	mos6par.c	\
	mos6set.c	\
	mos6temp.c	\
	mos6trun.c

HDRS = \
	mos6defs.h	\
	mos6ext.h	\
	mos6init.h	\
	mos6itf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
