
TARGET = mes
$(TARGET):

###include makedefs
CFILES = \
mes.c \
mesacl.c \
mesask.c \
mesdisto.c \
mesdset.c \
mesgetic.c \
mesload.c \
mesmask.c \
mesmpar.c \
mesnoise.c \
mesparam.c \
mesparse.c \
mespzld.c \
messetup.c \
mestemp.c \
mestrunc.c

HDRS = \
mesdefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
