
TARGET = ind
$(TARGET):

###include makedefs
CFILES = \
	ind.c		\
	indacld.c	\
	indask.c	\
	inddel.c	\
	inddest.c	\
	indinit.c	\
	indload.c	\
	indmask.c	\
	indmdel.c	\
	indmpar.c	\
	indparam.c	\
	indpzld.c	\
	indsacl.c	\
	indsetup.c	\
	indsload.c	\
	indsprt.c	\
	indsset.c	\
	indsupd.c	\
	indtemp.c	\
	indtrunc.c	\
	mutacld.c	\
	mutask.c	\
	mutdel.c	\
	mutdest.c	\
	mutmdel.c	\
	mutparam.c	\
	mutpzld.c	\
	mutsetup.c	\
	mutsprt.c	\
	mutsset.c	\
	muttemp.c

HDRS = \
	inddefs.h	\
	indext.h	\
	indinit.h	\
	inditf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
