
TARGET = hisim
$(TARGET):

###include makedefs
CFILES = \
	hsm1.c		\
	hsm1acld.c	\
	hsm1ask.c 	\
	hsm1cvtest.c 	\
	hsm1del.c 	\
	hsm1dest.c 	\
	hsm1eval102.c	\
	hsm1eval112.c 	\
	hsm1eval120.c 	\
	hsm1getic.c 	\
	hsm1init.c 	\
	hsm1ld.c 	\
	hsm1mask.c 	\
	hsm1mdel.c 	\
	hsm1mpar.c 	\
	hsm1noi.c 	\
	hsm1par.c 	\
	hsm1pzld.c 	\
	hsm1set.c 	\
	hsm1temp.c 	\
	hsm1trunc.c

HDRS = \
	hisim.h		\
	hsm1def.h	\
	hsm1evalenv.h	\
	hsm1ext.h	\
	hsm1init.h	\
	hsm1itf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
