
TARGET = soi3
$(TARGET):

###include makedefs
CFILES = \
	soi3.c		\
	soi3acld.c	\
	soi3ask.c	\
	soi3cap.c	\
	soi3conv.c	\
	soi3del.c	\
	soi3dest.c	\
	soi3ic.c	\
	soi3init.c	\
	soi3load.c	\
	soi3mask.c	\
	soi3mdel.c	\
	soi3mpar.c	\
	soi3nois.c	\
	soi3par.c	\
	soi3set.c	\
	soi3temp.c	\
	soi3trun.c

HDRS = \
	soi3defs.h	\
	soi3ext.h	\
	soi3init.h	\
	soi3itf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
