
TARGET = mesa
$(TARGET):

###include makedefs
CFILES = \
	mesa.c		\
	mesaacl.c	\
	mesaask.c	\
	mesadel.c	\
	mesadest.c	\
	mesagetic.c	\
	mesainit.c	\
	mesaload.c	\
	mesamask.c	\
	mesamdel.c	\
	mesamparam.c	\
	mesaparam.c	\
	mesapzl.c	\
	mesasetup.c	\
	mesatemp.c	\
	mesatrunc.c

HDRS = \
	mesadefs.h	\
	mesaext.h	\
	mesainit.h	\
	mesaitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
