
TARGET = bsim3soi
$(TARGET):

###include makedefs
CFILES = \
	b3soi.c	\
	b3soiacld.c	\
	b3soiask.c	\
	b3soicheck.c	\
	b3soicvtest.c	\
	b3soidel.c	\
	b3soidest.c	\
	b3soigetic.c	\
	b3soild.c	\
	b3soimask.c	\
	b3soimdel.c	\
	b3soimpar.c	\
	b3soinoi.c	\
	b3soipar.c	\
	b3soipzld.c	\
	b3soiset.c	\
	b3soitemp.c	\
	b3soitrunc.c	\
	b3soiinit.c

HDRS = \
	b3soidef.h	\
	b3soiext.h	\
	b3soiinit.h	\
	b3soiitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
