
TARGET = ltra
$(TARGET):

###include makedefs
CFILES = \
ltra.c \
ltraacct.c \
ltraacld.c \
ltraask.c \
ltradel.c \
ltradest.c \
ltraload.c \
ltramask.c \
ltramdel.c \
ltramisc.c \
ltrampar.c \
ltrapar.c \
ltraprse.c \
ltraset.c \
ltratrun.c

HDRS = \
ltradefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
