
TARGET = bsim1
$(TARGET):

###include makedefs
CFILES = \
b1.c \
b1acld.c \
b1ask.c \
b1cvtest.c \
b1disto.c \
b1dset.c \
b1eval.c \
b1getic.c \
b1ld.c \
b1mask.c \
b1moscap.c \
b1mpar.c \
b1par.c \
b1pzld.c \
b1set.c \
b1temp.c \
b1trunc.c

HDRS = \
bsim1def.h \
wrapper.h


SPICE_VERSION = JSPICE3

include ../Make2
