
TARGET = cap
$(TARGET):

###include makedefs
CFILES = \
cap.c \
capacld.c \
capask.c \
capgetic.c \
capload.c \
capmask.c \
capmpar.c \
capparam.c \
capparse.c \
cappzld.c \
capsetup.c \
captemp.c \
captrunc.c

HDRS = \
capdefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
