
TARGET = bjt2
$(TARGET):

###include makedefs
CFILES = \
	bjt2.c		\
	bjt2acld.c	\
	bjt2ask.c	\
	bjt2conv.c	\
	bjt2del.c	\
	bjt2dest.c	\
	bjt2disto.c	\
	bjt2dset.c	\
	bjt2getic.c	\
	bjt2init.c	\
	bjt2load.c	\
	bjt2mask.c	\
	bjt2mdel.c	\
	bjt2mpar.c	\
	bjt2noise.c	\
	bjt2param.c	\
	bjt2pzld.c	\
	bjt2sacl.c      \
	bjt2setup.c	\
	bjt2sload.c     \
	bjt2sprt.c      \
	bjt2sset.c      \
	bjt2supd.c      \
	bjt2temp.c	\
	bjt2trun.c

HDRS = \
	bjt2defs.h	\
	bjt2dset.h	\
	bjt2ext.h	\
	bjt2init.h	\
	bjt2itf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
