
TARGET = urc
$(TARGET):

###include makedefs
CFILES = \
urc.c \
urcask.c \
urcdel.c \
urcmask.c \
urcmpar.c \
urcparam.c \
urcparse.c \
urcsetup.c

HDRS = \
urcdefs.h \
wrapper.h

SPICE_VERSION = JSPICE3

include ../Make2
