
TARGET = bsim3soidd
$(TARGET):

###include makedefs
CFILES = \
	b3soidd.c	\
	b3soiddacld.c	\
	b3soiddask.c	\
	b3soiddcheck.c	\
	b3soiddcvtest.c	\
	b3soidddel.c	\
	b3soidddest.c	\
	b3soiddgetic.c	\
	b3soiddld.c	\
	b3soiddmask.c	\
	b3soiddmdel.c	\
	b3soiddmpar.c	\
	b3soiddnoi.c	\
	b3soiddpar.c	\
	b3soiddpzld.c	\
	b3soiddset.c	\
	b3soiddtemp.c	\
	b3soiddtrunc.c	\
	b3soiddinit.c

HDRS = \
	b3soidddef.h	\
	b3soiddext.h	\
	b3soiddinit.h	\
	b3soidditf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
