
TARGET = bsim4
$(TARGET):

###include makedefs
CFILES = \
	b4.c		\
	b4acld.c	\
	b4ask.c		\
	b4check.c	\
	b4cvtest.c	\
	b4del.c		\
	b4dest.c	\
	b4geo.c		\
	b4getic.c	\
	b4ld.c		\
	b4mask.c	\
	b4mdel.c	\
	b4mpar.c	\
	b4noi.c		\
	b4par.c		\
	b4pzld.c	\
	b4set.c		\
	b4temp.c	\
	b4trunc.c	\
	bsim4init.c

HDRS = \
	bsim4def.h	\
	bsim4ext.h	\
	bsim4init.h	\
	bsim4itf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
