
TARGET = hfet2
$(TARGET):

###include makedefs
CFILES = \
	hfet2.c		\
	hfet2acl.c	\
	hfet2ask.c	\
	hfet2del.c	\
	hfet2dest.c	\
	hfet2getic.c	\
	hfet2init.c	\
	hfet2load.c	\
	hfet2mask.c	\
	hfet2mdel.c	\
	hfet2mpar.c	\
	hfet2param.c	\
	hfet2pzl.c	\
	hfet2setup.c	\
	hfet2temp.c	\
	hfet2trunc.c

HDRS = \
	hfet2defs.h	\
	hfet2ext.h	\
	hfet2init.h	\
	hfet2itf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
