
TARGET = bsim3soifd
$(TARGET):

###include makedefs
CFILES = \
	b3soifd.c	\
	b3soifdacld.c	\
	b3soifdask.c	\
	b3soifdcheck.c	\
	b3soifdcvtest.c	\
	b3soifddel.c	\
	b3soifddest.c	\
	b3soifdgetic.c	\
	b3soifdld.c	\
	b3soifdmask.c	\
	b3soifdmdel.c	\
	b3soifdmpar.c	\
	b3soifdnoi.c	\
	b3soifdpar.c	\
	b3soifdpzld.c	\
	b3soifdset.c	\
	b3soifdtemp.c	\
	b3soifdtrunc.c	\
	b3soifdinit.c

HDRS = \
	b3soifddef.h	\
	b3soifdext.h	\
	b3soifdinit.h	\
	b3soifditf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
