
TARGET = hfet
$(TARGET):

###include makedefs
CFILES = \
	hfet.c		\
	hfetacl.c	\
	hfetask.c	\
	hfetdel.c	\
	hfetdest.c	\
	hfetgetic.c	\
	hfetinit.c	\
	hfetload.c	\
	hfetmask.c	\
	hfetmdel.c	\
	hfetmpar.c	\
	hfetparam.c	\
	hfetpzl.c	\
	hfetsetup.c	\
	hfettemp.c	\
	hfettrunc.c

HDRS = \
	hfetdefs.h	\
	hfetext.h	\
	hfetinit.h	\
	hfetitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
