
TARGET = cccs
$(TARGET):

###include makedefs
CFILES = \
	cccs.c		\
	cccsask.c	\
	cccsdel.c	\
	cccsdest.c	\
	cccsinit.c	\
	cccsload.c	\
	cccsmdel.c	\
	cccspar.c	\
	cccspzld.c	\
	cccssacl.c	\
	cccsset.c	\
	cccssld.c	\
	cccssprt.c	\
	cccssset.c

HDRS = \
	cccsdefs.h	\
	cccsext.h	\
	cccsinit.h	\
	cccsitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE_17

include ../Make2
